@startuml
package "Repositorio DevOps" {
    [Angular Front - End] - [Spring Boot Back - End]
    [Spring Boot Back - End] - [PostgreSQL Database]
    [Spring Boot Back - End] - [Jenkins CI/CD System]
}

package "External Services" {
    [GitHub]
    [DockerHub]
}

[Angular Front - End] --> [Spring Boot Back - End]
[Spring Boot Back - End] --> [PostgreSQL Database]
[Spring Boot Back - End] --> [Jenkins CI/CD System]

[Jenkins CI/CD System] --> [GitHub]
[Jenkins CI/CD System] --> [DockerHub]
@enduml
