@startuml
node "Client" {
    [Web Browser]
}

node "Web Server" {
    [Angular Front - End]
    [Spring Boot Back - End]
}

node "Microservices Server" {
    [Microservice authentication] as m1
    [Resource Management Microservice] as m2
    [Statistics and Analysis Microservice] as m3
}

node "Database Server" {
    [PostgreSQL]
}

node "CI/CD Server" {
    [Jenkins]
}

node "External Services" {
    [GitHub]
    [DockerHub]
}

[Web Browser] --> [Angular Front - End] : HTTP Request
[Angular Front - End] --> [Spring Boot Back - End] : API Calls
[Spring Boot Back - End] --> [PostgreSQL] : SQL Queries
[Spring Boot Back - End] --> m1 : API Call
[Spring Boot Back - End] --> m2 : API Call
[Spring Boot Back - End] --> m3 : API Call
[Spring Boot Back - End] --> [Jenkins] : Jobs
[Jenkins] --> [GitHub] : Push/Pull Code
[Jenkins] --> [DockerHub] : Push/Pull Images
@enduml
